build: pending_signal.c sigaction_flags.c siginterrupt.c
	mkdir -p build
	cc -g pending_signal.c -o  build/pending_signal
	cc -g sigaction_flags.c -o build/sigaction_flags
	cc -g siginterrupt.c -o build/siginterrupt
