build: common.h write_append.c dup2.c readv.c writev.c
	mkdir -p build
	cc -g write_append.c -o build/write_append
	cc -g dup2.c -o build/dup2
	cc -g readv.c -o build/readv
	cc -g writev.c -o build/writev